services:
    db:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - mysql_data:/var/lib/mysql

    backend:
        build: .
        depends_on:
            - db
        ports:
            - 8000:8000
        env_file:
            - .env
        volumes:
            - backend_data:/app/.venv/

        develop:
            watch:
                - action: sync
                  path: .
                  target: /app
                - action: rebuild
                  path: requirements.txt
                - action: rebuild
                  path: Dockerfile
                - action: rebuild
                  path: run_server.sh

volumes:
    mysql_data:
    backend_data:
