# Generated by Django 5.2 on 2025-04-13 11:43

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    group_names = ["Employees", "Managers", "ScheduleAdmins", "Admins"]
    for name in group_names:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
